Repository Matteas-Eden/roll-for-reaction, pull requests merged in 2020-03, with the labels that each got.

#2 Create Templates closes #1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#4 Change from MIT license to GNU license
  LICENSE
Labels: enhancement

#18 Update README.md closes #5, #9
  README.md
Labels: documentation

#20 Create Logo closes #10
  public/logo.png
Labels: asset, design, feature

#17 Make improvements to the code base
  .all-contributorsrc
  .eslintrc.yml
  .nvmrc
  .prettierrc
  buildspec.staging.yml
  buildspec.yml
  config-overrides.js
  docs/CONTRIBUTING.md
  docs/DEPENDENCIES.md
  docs/VISION.md
  docs/depends.py
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  public/sitemap.xml
  src/App.js
  src/components/download-app-popup/assets/android-store.png
  src/components/download-app-popup/assets/ios-store.png
  src/components/download-app-popup/index.js
  src/components/download-app-popup/styles.scss
  src/components/footer/index.js
  src/features/dialog-manager/dialogs/game-select/index.js
  src/features/game-menus/game-music/index.js
  src/features/map/index.js
  src/index.js
  yarn.lock
Labels: documentation, enhancement

#22 Create new favicon closes #19
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/favicon.png
  public/index.html
  public/manifest.json
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  src/components/footer/index.js
  src/features/dialog-manager/dialogs/game-select/index.js
  src/features/map/index.js
  yarn.lock
Labels: asset, feature

#25 Create .all-contributorsrc and add bot closes #23
  .all-contributorsrc
Labels: feature

#30 Privacy policy
  package.json
  yarn.lock
Labels: admin, dependency, good first issue

#36 Generate contributions using all-contributors-cli
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: admin, dependency, documentation

#35 Install and setup gh-pages build closes #7
  package.json
  public/index.html
  public/manifest.json
  src/features/map/map-padding.js
  src/features/map/map-tile.js
  yarn.lock
Labels: admin, dependency, feature

#31 Logo in Readme
  README.md
  public/logo/logo-wide-no-background.png
  public/logo/logo-wide.png
  public/logo/logo.png
Labels: documentation

#40 Added Meeting Minutes Template
  .github/meeting_minutes_template.md
Labels: documentation

#41 Update contributions and add relevant information
  .all-contributorsrc
  README.md
  docs/CONTRIBUTIONS.md
Labels: admin, documentation

#43 Add developer instructions closes #34
  README.md
Labels: documentation

#52 Update documentation and migrate to wiki closes #44
  README.md
  docs/CONTRIBUTING.md
  docs/CONTRIBUTIONS.md
  docs/DEPENDENCIES.md
  docs/ROADMAP.md
  docs/VISION.md
  docs/depends.py
Labels: documentation
