Repository Matteas-Eden/roll-for-reaction, pull requests merged in 2020-05, with the labels that each got.

#185 Modify defence calculation
  src/features/stats/reducer.js
  src/utils/calculate-defence-bonus.js
Labels: bug, enhancement

#190 Enhancement/tiers closes #187
  src/components/shop-inventory/shop-items.js
  src/config/constants.js
  src/data/items/clothes/armor/iron-armor/index.js
  src/data/items/clothes/armor/iron-armor/iron-armor.png
  src/data/items/clothes/armor/iron-boots/index.js
  src/data/items/clothes/armor/iron-boots/iron-boots.png
  src/data/items/clothes/armor/iron-gloves/index.js
  src/data/items/clothes/armor/iron-gloves/iron-gloves.png
  src/data/items/clothes/armor/iron-helm/index.js
  src/data/items/clothes/armor/iron-helm/iron-helm.png
  src/data/items/clothes/armor/iron-pants/index.js
  src/data/items/clothes/armor/iron-pants/iron-pants.png
  src/data/items/clothes/armor/mithril-armor/index.js
  src/data/items/clothes/armor/mithril-armor/mithril-armor.png
  src/data/items/clothes/armor/mithril-boots/index.js
  src/data/items/clothes/armor/mithril-boots/mithril-boots.png
  src/data/items/clothes/armor/mithril-gloves/index.js
  src/data/items/clothes/armor/mithril-gloves/mithril-gloves.png
  src/data/items/clothes/armor/mithril-helm/index.js
  src/data/items/clothes/armor/mithril-helm/mithril-helm.png
  src/data/items/clothes/armor/mithril-pants/index.js
  src/data/items/clothes/armor/mithril-pants/mithril-pants.png
  src/data/items/clothes/armor/steel-armor/index.js
  src/data/items/clothes/armor/steel-armor/steel-armor.png
  src/data/items/clothes/armor/steel-boots/index.js
  src/data/items/clothes/armor/steel-boots/steel-boots.png
  src/data/items/clothes/armor/steel-gloves/index.js
  src/data/items/clothes/armor/steel-gloves/steel-gloves.png
  src/data/items/clothes/armor/steel-helm/index.js
  src/data/items/clothes/armor/steel-helm/steel-helm.png
  src/data/items/clothes/armor/steel-pants/index.js
  src/data/items/clothes/armor/steel-pants/steel-pants.png
  src/data/items/index.js
  src/features/dialog-manager/dialogs/chest-loot/random-item.js
Labels: asset, enhancement

#175 Implement Mana Regeneration
  package.json
  src/components/shop-inventory/shop-items.js
  src/components/view-item/index.js
  src/config/constants.js
  src/data/items/clothes/robes/black-robes/index.js
  src/data/items/clothes/robes/brown-robes/index.js
  src/data/items/clothes/robes/red-robes/index.js
  src/data/items/clothes/robes/skull-robes/index.js
  src/data/items/clothes/robes/teal-robes/index.js
  src/data/items/index.js
  src/data/items/other/spellbook/index.js
  src/data/items/potions/divine-hp-potion/index.js
  src/data/items/potions/divine-mana-potion/index.js
  src/data/items/potions/divine-mp-potion/divine-mp-potion.png
  src/data/items/potions/divine-mp-potion/index.js
  src/data/items/potions/great-hp-potion/index.js
  src/data/items/potions/great-mp-potion/great-mp-potion.png
  src/data/items/potions/great-mp-potion/index.js
  src/data/items/potions/hp-potion/index.js
  src/data/items/potions/mighty-hp-potion/index.js
  src/data/items/potions/mighty-mana-potion/index.js
  src/data/items/potions/mighty-mp-potion/index.js
  src/data/items/potions/mighty-mp-potion/mighty-mp-potion.png
  src/data/items/potions/mp-potion/index.js
  src/data/items/potions/mp-potion/mp-potion.png
  src/data/items/weapons/ranged/boomerang/index.js
  src/data/items/weapons/ranged/bow/index.js
  src/data/items/weapons/ranged/crossbow/index.js
  src/data/items/weapons/ranged/slingshot/index.js
  src/data/items/weapons/staffs/black-staff/index.js
  src/data/items/weapons/staffs/brown-staff/index.js
  src/data/items/weapons/staffs/red-staff/index.js
  src/data/items/weapons/staffs/skull-staff/index.js
  src/data/items/weapons/staffs/teal-staff/index.js
  src/data/spells/fireball/index.js
  src/data/spells/mend/index.js
  src/features/inventory/actions/consume-potion.js
  src/features/player/actions/move-player.js
  src/features/player/reducer.js
  src/features/stats/reducer.js
  yarn.lock
Labels: feature

#173 Enhance the Journal for Readability
  src/features/dialog-manager/actions/log-level-up.js
  src/features/dialog-manager/actions/set-journal-scrolling.js
  src/features/dialog-manager/dialogs/journal-dialog/index.js
  src/features/dialog-manager/dialogs/journal-dialog/styles.scss
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/dialog-manager/index.js
  src/features/journal/reducer.js
  src/features/monsters/actions/attack-player.js
  src/features/player/actions/attack-monster.js
  src/features/player/actions/cast-spell.js
  src/features/stats/reducer.js
Labels: enhancement, usability

#194 Enhancement/starting items
  README.md
  src/features/dialog-manager/dialogs/game-instructions/index.js
  src/features/inventory/actions/load-starting-items.js
  src/features/inventory/reducer.js
  src/features/snackbar/index.js
Labels: enhancement

#196 Only move player when not in combat or facing same direction
  src/features/player/actions/move-player.js
Labels: enhancement

#204 Rework features in table closes #202
  README.md
Labels: documentation

#209 Modify shopkeeper sprite animation closes #189
  src/components/shop-keep/shop-keep.png
  src/components/shop-keep/styles.scss
Labels: enhancement

#210 Add Mana Cost to Spell View
  src/components/view-item/index.js
  src/components/view-item/stats-item/index.js
  src/index.scss
Labels: enhancement

#211 Add new enemies
  README.md
  src/data/maps/1_1/index.js
  src/data/maps/1_2/index.js
  src/data/maps/1_3/index.js
  src/data/maps/1_4/index.js
  src/data/maps/1_5/index.js
  src/data/maps/2_1/index.js
  src/data/maps/2_2/index.js
  src/data/maps/2_3/index.js
  src/data/monsters/bat/bat.png
  src/data/monsters/bat/index.js
  src/data/monsters/black-orc/black-orc.png
  src/data/monsters/black-orc/index.js
  src/data/monsters/cerberus/cerberus.png
  src/data/monsters/cerberus/index.js
  src/data/monsters/ghost/ghost.png
  src/data/monsters/ghost/index.js
  src/data/monsters/goblin/index.js
  src/data/monsters/imp/index.js
  src/data/monsters/index.js
  src/data/monsters/medusa/index.js
  src/data/monsters/medusa/medusa.png
  src/data/monsters/orc/index.js
  src/data/monsters/orc/orc.png
  src/data/monsters/rat/index.js
  src/data/monsters/warlock/index.js
  src/data/monsters/warlock/warlock.png
  src/data/monsters/wolf/index.js
  src/data/monsters/wolf/wolf.png
Labels: asset, design, feature

#201 Implement Ranged Attacks
  src/components/animation/index.js
  src/components/journal-side/index.js
  src/components/journal-side/styles.scss
  src/data/items/index.js
  src/data/items/weapons/ranged/boomerang/boomerang-animated.png
  src/data/items/weapons/ranged/boomerang/index.js
  src/data/items/weapons/ranged/bow/arrow.png
  src/data/items/weapons/ranged/bow/index.js
  src/data/items/weapons/ranged/crossbow/bolt.png
  src/data/items/weapons/ranged/crossbow/index.js
  src/data/items/weapons/ranged/slingshot/index.js
  src/data/items/weapons/ranged/slingshot/stone.png
  src/data/items/weapons/swords/broad-sword/index.js
  src/data/items/weapons/swords/dragons-bane/index.js
  src/data/items/weapons/swords/lich-bane/index.js
  src/data/items/weapons/swords/rusty-sword/index.js
  src/data/items/weapons/swords/steel-sword/index.js
  src/data/spells/fireball/index.js
  src/features/dialog-manager/dialogs/character-creation/index.js
  src/features/dialog-manager/dialogs/journal-dialog/entry-styles.scss
  src/features/dialog-manager/dialogs/journal-dialog/index.js
  src/features/dialog-manager/dialogs/journal-dialog/styles.scss
  src/features/inventory/actions/load-starting-items.js
  src/features/journal/reducer.js
  src/features/player/actions/attack-monster.js
  src/features/player/actions/cast-spell.js
  src/features/player/index.js
  src/features/player/reducer.js
  src/features/stats/reducer.js
Labels: feature

#214 Add new Spells to the Spell Book
  src/components/view-item/index.js
  src/components/view-item/stats-item/index.js
  src/components/view-item/stats-item/styles.scss
  src/components/view-item/styles.scss
  src/config/constants.js
  src/data/items/weapons/staffs/black-staff/index.js
  src/data/items/weapons/staffs/brown-staff/index.js
  src/data/items/weapons/staffs/red-staff/index.js
  src/data/items/weapons/staffs/skull-staff/index.js
  src/data/items/weapons/staffs/teal-staff/index.js
  src/data/monsters/bat/index.js
  src/data/monsters/black-orc/index.js
  src/data/monsters/cerberus/index.js
  src/data/monsters/dragon/index.js
  src/data/monsters/ghost/index.js
  src/data/monsters/goblin/index.js
  src/data/monsters/imp/index.js
  src/data/monsters/lich/index.js
  src/data/monsters/medusa/index.js
  src/data/monsters/orc/index.js
  src/data/monsters/rat/index.js
  src/data/monsters/stone-golem/index.js
  src/data/monsters/warlock/index.js
  src/data/monsters/wolf/index.js
  src/data/spells/fireball/index.js
  src/data/spells/ice-shard/IceShard-image.png
  src/data/spells/ice-shard/IceShard.png
  src/data/spells/ice-shard/index.js
  src/data/spells/index.js
  src/data/spells/lightning-bolt/LightningBolt-image.png
  src/data/spells/lightning-bolt/LightningBolt.png
  src/data/spells/lightning-bolt/index.js
  src/data/spells/mend/index.js
  src/data/spells/poison-dart/PoisonDart-image.png
  src/data/spells/poison-dart/PoisonDart.png
  src/data/spells/poison-dart/index.js
  src/data/spells/void/Void-image.png
  src/data/spells/void/Void.png
  src/data/spells/void/index.js
  src/features/dialog-manager/dialogs/journal-dialog/entry-styles.scss
  src/features/dialog-manager/dialogs/spellbook-dialog/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/spell-button/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/spell-button/styles.scss
  src/features/dialog-manager/dialogs/spellbook-dialog/styles.scss
  src/features/journal/reducer.js
  src/features/monsters/actions/attack-monster.js
  src/features/monsters/actions/frozen-ai.js
  src/features/monsters/actions/move-monster.js
  src/features/monsters/actions/normal-ai.js
  src/features/monsters/actions/poisoned-ai.js
  src/features/monsters/actions/scared-ai.js
  src/features/monsters/actions/shocked-ai.js
  src/features/monsters/actions/take-monsters-turn.js
  src/features/monsters/reducer.js
  src/features/player/actions/attack-monster.js
  src/features/player/actions/cast-spell.js
  src/features/player/index.js
  src/features/snackbar/reducer.js
  src/features/stats/reducer.js
Labels: enhancement

#218 Equipping a weapon causes the game to crash
  src/features/stats/reducer.js
Labels: bug

#223 Decrease levels between ability point gain and starting abilities
  src/config/constants.js
  src/features/journal/reducer.js
  src/utils/is-ability-allocation-level.js
Labels: enhancement

#220 Enhancement/increase level 1
  src/config/constants.js
  src/utils/calculate-max-hp-pool.js
  src/utils/calculate-max-mana-pool.js
Labels: Low Priority, enhancement, usability

#221 Change enemy attack value to dice rolls
  src/data/monsters/bat/index.js
  src/data/monsters/black-orc/index.js
  src/data/monsters/cerberus/index.js
  src/data/monsters/dragon/index.js
  src/data/monsters/fire-spirit/index.js
  src/data/monsters/fungi-bulb/index.js
  src/data/monsters/gas-cloud/index.js
  src/data/monsters/ghost/index.js
  src/data/monsters/goblin/index.js
  src/data/monsters/imp/index.js
  src/data/monsters/lich/index.js
  src/data/monsters/medusa/index.js
  src/data/monsters/orc/index.js
  src/data/monsters/plantera/index.js
  src/data/monsters/poison-cloud/index.js
  src/data/monsters/rat/index.js
  src/data/monsters/salamander/index.js
  src/data/monsters/snake/index.js
  src/data/monsters/stone-golem/index.js
  src/data/monsters/warlock/index.js
  src/data/monsters/water-spirit/index.js
  src/data/monsters/wolf/index.js
  src/features/journal/reducer.js
  src/features/monsters/actions/attack-player.js
Labels: enhancement

#238 Add More Spells
  src/data/spells/blizzard/Blizzard-image.png
  src/data/spells/blizzard/Blizzard.png
  src/data/spells/blizzard/index.js
  src/data/spells/frighten/Frighten-image.png
  src/data/spells/frighten/Frighten.png
  src/data/spells/frighten/index.js
  src/data/spells/heal/Heal-image.png
  src/data/spells/heal/Heal.png
  src/data/spells/heal/index.js
  src/data/spells/index.js
  src/data/spells/meteor/Meteor-image.png
  src/data/spells/meteor/Meteor.png
  src/data/spells/meteor/index.js
  src/data/spells/poison-cloud/PoisonCloud-image.png
  src/data/spells/poison-cloud/PoisonCloud.png
  src/data/spells/poison-cloud/index.js
  src/data/spells/thunder-storm/ThunderStorm-image.png
  src/data/spells/thunder-storm/ThunderStorm.png
  src/data/spells/thunder-storm/index.js
  src/data/spells/void/index.js
  src/features/monsters/actions/frightened-ai.js
  src/features/monsters/actions/take-monsters-turn.js
Labels: enhancement

#243 Swap level and defence location
  src/features/stats/index.js
Labels: design, enhancement

#230 Add critical hits
  src/features/journal/reducer.js
  src/features/player/actions/attack-monster.js
  src/features/player/actions/cast-spell.js
  src/utils/dice.js
Labels: design, enhancement, feature

#241 Enahncement/change ending message
  src/data/maps/1/2/index.js
  src/data/maps/1/4/index.js
  src/data/maps/1/5/index.js
  src/data/maps/4/1/index.js
  src/data/maps/4/4/index.js
  src/data/maps/5/1/index.js
  src/data/maps/5/3/index.js
  src/data/maps/5/4/index.js
  src/data/maps/5/5/index.js
  src/features/dialog-manager/dialogs/game-win/index.js
  src/features/dialog-manager/dialogs/game-win/styles.scss
Labels: design, enhancement

#247 Modify to blink only on level up
  src/features/dialog-manager/dialogs/game-win/index.js
  src/features/stats/index.js
Labels: enhancement, usability

#226 Provide Enhancements to the Journal
  src/App.js
  src/components/footer/styles.scss
  src/components/journal-side/index.js
  src/components/view-item/stats-item/index.js
  src/config/constants.js
  src/features/dialog-manager/actions/toggle-journal.js
  src/features/dialog-manager/index.js
  src/features/dialog-manager/reducer.js
  src/features/game-menus/index.js
  src/features/journal/index.js
  src/features/journal/reducer.js
  src/features/player/actions/cast-spell.js
Labels: bug, enhancement

#248 Fix Loading Games
  src/App.js
  src/config/constants.js
  src/features/journal/reducer.js
Labels: bug

#250 Change bow to crossbow in tutorial item page fixes #249
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/item-tutorial.js
Labels: bug

#254 Alter monster name
  src/data/items/weapons/ranged/hells-phoenix/index.js
  src/data/maps/5/3/index.js
Labels: bug

#255 Organise shop items
  src/components/shop-inventory/shop-items.js
  src/data/items/index.js
Labels: enhancement, usability

#259 Enhancement/map fixes
  public/tiles/walls/credits.txt
  src/data/items/weapons/ranged/crossbow/index.js
  src/data/items/weapons/ranged/hells-phoenix/index.js
  src/data/items/weapons/ranged/midnights-fury/index.js
  src/data/maps/1/1/index.js
  src/data/maps/1/2/index.js
  src/data/maps/1/3/index.js
  src/data/maps/1/4/index.js
  src/data/maps/1/5/index.js
  src/data/maps/2/1/index.js
  src/data/maps/2/3/index.js
  src/data/maps/2/4/index.js
  src/data/maps/2/5/index.js
  src/data/maps/3/1/index.js
  src/data/maps/3/2/index.js
  src/data/maps/3/3/index.js
  src/data/maps/3/4/index.js
  src/data/maps/3/5/index.js
  src/data/maps/4/1/index.js
  src/data/maps/4/2/index.js
  src/data/maps/4/4/index.js
  src/data/maps/4/5/index.js
  src/data/maps/5/1/index.js
  src/data/maps/5/2/index.js
  src/data/maps/5/3/index.js
Labels: design, enhancement

#258 Add More Tests to the Test Suite
  src/__tests__/utils/calculate-ability-modifier.js
  src/__tests__/utils/calculate-dice.js
  src/__tests__/utils/calculate-wisdom-potion-bonus.js
  src/__tests__/utils/calculate_dice.js
  src/utils/dice.js
Labels: enhancement, tests

#263 Decrease bow damage
  src/data/items/weapons/ranged/boomerang/index.js
Labels: bug

#266 Mana regen occurs every 10 out of combat turns
  src/config/constants.js
  src/features/player/actions/move-player.js
Labels: Balancing

#260 Make improvements to the tutorial closes #253
  src/App.js
  src/components/ability/styles.scss
  src/features/dialog-manager/dialogs/ability-dialog/styles.scss
  src/features/dialog-manager/dialogs/tutorial-dialog/actions/get-next-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/actions/get-previous-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/index.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/dice-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/shop-tutorial.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/styles.scss
Labels: documentation, enhancement

#268 Add story floor counter
  src/App.js
  src/components/endless-floor-counter/styles.scss
  src/components/floor-counter/index.js
  src/components/floor-counter/styles.scss
Labels: enhancement

#278 Limit number of items in shop
  src/data/items/index.js
Labels: design, usability

#265 Snitch on the Monsters
  src/features/dialog-manager/dialogs/game-over/index.js
  src/features/dialog-manager/dialogs/game-over/styles.scss
  src/features/dialog-manager/reducer.js
  src/features/monsters/actions/attack-player.js
  src/features/monsters/actions/monster-cast-spell.js
  src/features/monsters/actions/suicidal-ai.js
Labels: enhancement

#293 Change 'Value' to 'Price' in item display
  src/components/view-item/index.js
  src/components/view-item/stats-item/index.js
Labels: enhancement

#294 Change ranged weapon prices
  src/data/items/weapons/ranged/boomerang/index.js
  src/data/items/weapons/ranged/crossbow/index.js
  src/data/items/weapons/ranged/hells-phoenix/index.js
  src/data/items/weapons/ranged/slingshot/index.js
Labels: bug

#295 Enhancement/shop locations
  src/data/maps/2/5/index.js
  src/data/maps/3/5/index.js
  src/data/maps/4/5/index.js
  src/data/maps/5/2/index.js
  src/data/maps/5/5/index.js
Labels: design

#273 Bug Fixing
  src/components/view-item/index.js
  src/features/journal/reducer.js
  src/features/monsters/actions/frightened-ai.js
  src/features/monsters/actions/frozen-ai.js
  src/features/monsters/actions/magical-ai.js
  src/features/monsters/actions/move-monster.js
  src/features/monsters/actions/poisoned-ai.js
  src/features/monsters/actions/ranged-ai.js
  src/features/monsters/actions/scared-ai.js
  src/features/monsters/actions/shocked-ai.js
  src/features/player/actions/attack-monster.js
  src/features/player/actions/cast-spell.js
Labels: bug

#296 Balance Spells
  src/data/spells/blizzard/index.js
  src/data/spells/fireball/index.js
  src/data/spells/frighten/index.js
  src/data/spells/heal/index.js
  src/data/spells/ice-shard/index.js
  src/data/spells/lightning-bolt/index.js
  src/data/spells/mend/index.js
  src/data/spells/meteor/index.js
  src/data/spells/poison-cloud/index.js
  src/data/spells/poison-dart/index.js
  src/data/spells/thunder-storm/index.js
  src/data/spells/void/index.js
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/dialog-manager/dialogs/level-up/styles.scss
  src/features/journal/reducer.js
  src/features/player/actions/cast-spell.js
Labels: Balancing, design, enhancement

#277 Fix Bugs with the AI and Effects
  src/features/dialog-manager/dialogs/game-over/index.js
  src/features/dialog-manager/reducer.js
  src/features/monsters/actions/frightened-ai.js
  src/features/player/actions/move-player.js
Labels: bug

#300 Add tooltips to character creation screen closes #285
  src/features/dialog-manager/dialogs/character-creation/index.js
  src/features/dialog-manager/dialogs/character-creation/styles.scss
Labels: enhancement

#302 Enhancement/potion values
  src/components/view-item/index.js
  src/data/items/potions/divine-hp-potion/index.js
  src/data/items/potions/divine-mp-potion/index.js
  src/features/inventory/actions/consume-potion.js
Labels: enhancement

#306 Balance/level 30
  src/components/view-item/index.js
  src/data/maps/3/3/index.js
  src/data/maps/4/2/index.js
  src/data/maps/4/3/index.js
  src/data/maps/4/4/index.js
  src/data/maps/5/1/index.js
Labels: Balancing

#311 Add tutorial buttons to game select screens closes #281
  src/App.js
  src/features/dialog-manager/actions/confirm-ability-score-dialog.js
  src/features/dialog-manager/actions/toggle-tutorial.js
  src/features/dialog-manager/dialogs/endless-game-start/index.js
  src/features/dialog-manager/dialogs/main-game-start/index.js
  src/features/dialog-manager/reducer.js
  src/features/game-menus/index.js
Labels: enhancement

#309 Several Bug Fixes
  src/data/monsters/medusa/index.js
  src/data/monsters/medusa/medusa-flopped.png
  src/features/dialog-manager/dialogs/chest-loot/index.js
  src/features/dialog-manager/dialogs/chest-loot/styles.scss
  src/features/dialog-manager/dialogs/journal-dialog/entry-styles.scss
  src/features/journal/reducer.js
  src/features/monsters/actions/attack-player.js
  src/features/monsters/actions/healer-ai.js
  src/features/player/index.js
Labels: bug

#314 Bug/ring tiers
  src/data/items/index.js
  src/data/items/weapons/staffs/skull-staff/index.js
Labels: bug

#327 Change level colour to purple
  src/features/stats/styles.scss
Labels: design

#317 Asset/new ring
  src/data/items/index.js
  src/data/items/rings/amethyst-ring/index.js
  src/data/items/rings/diamond-ring/index.js
  src/data/items/rings/old-ring/index.js
  src/data/items/rings/saphire-ring/index.js
  src/data/items/rings/saphire-ring/saphire-ring.png
  src/features/inventory/actions/load-starting-items.js
Labels: asset

#329 Change hp to health
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/journal/reducer.js
Labels: design

#331 Design/close buttons
  src/components/button/index.js
  src/components/button/styles.scss
  src/features/inventory/index.js
  src/features/journal/index.js
Labels: design

#333 Center game window
  src/App.js
Labels: design, usability

#335 Make Journal Button Behave Correctly
  src/features/dialog-manager/actions/toggle-journal.js
  src/features/journal/index.js
Labels: bug

#334 Implement tutorial feedback closes #319
  src/features/dialog-manager/dialogs/tutorial-dialog/actions/get-next-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/actions/get-previous-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/ability-tutorial.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/assets/dice/d10.png
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/assets/dice/d20.png
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/assets/dice/d4.png
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/assets/dice/d6.png
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/assets/dice/d8.png
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/dice-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/hotkey-page.js
  src/features/dialog-manager/dialogs/tutorial-dialog/pages/styles.scss
Labels: enhancement
