Repository Matteas-Eden/roll-for-reaction, pull requests merged in 2020-04, with the labels that each got.

#54 Add continuous deployment closes #48
  .github/workflows/main.yml
Labels: admin

#63 Notification Adjustment
  src/components/footer/styles.scss
  src/features/snackbar/index.js
  src/features/snackbar/styles.scss
Labels: design, enhancement, usability

#67 Align stats box for smalls screens
  src/features/game-menus/index.js
  src/features/snackbar/index.js
Labels: design, usability

#69 Fix Empty Chests on Third Open
  src/features/world/reducer.js
Labels: bug

#75 Enhancement/ability score dialog
  src/components/ability/index.js
  src/components/ability/styles.scss
  src/config/constants.js
  src/features/dialog-manager/actions/ability-score-dialog.js
  src/features/dialog-manager/actions/set-ability-scores.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
  src/features/dialog-manager/dialogs/ability-dialog/styles.scss
  src/features/dialog-manager/dialogs/game-text-dialog/index.js
  src/features/dialog-manager/index.js
  src/features/dialog-manager/reducer.js
  src/features/stats/reducer.js
Labels: Low Priority, enhancement

#76 Link ability scores to UI
  src/features/stats/index.js
  src/utils/calculate-modifier.js
Labels: design, enhancement

#84 Alignment and font change
  package.json
  src/features/stats/index.js
  src/features/stats/styles.scss
  src/index.js
  src/index.scss
  yarn.lock
Labels: enhancement, usability

#86 Center chest
  src/data/maps/1_4/index.js
Labels: design, enhancement, good first issue

#78 Move Functions to src/utility
  src/config/constants.js
  src/features/dialog-manager/actions/open-chest.js
  src/features/inventory/actions/pickup-item.js
  src/features/player/actions/explore-chest.js
  src/features/world/reducer.js
  src/utils/get-chest-name.js
  src/utils/sprite-to-coordinates.js
Labels: Low Priority, enhancement, good first issue

#89 Add constant for ability points fixes #88
  src/config/constants.js
Labels: bug

#87 Enhancement/move ability dialog
  src/components/ability/styles.scss
  src/components/button/styles.scss
  src/features/dialog-manager/actions/ability-score-dialog.js
  src/features/dialog-manager/actions/abilityScoreDialog.js
  src/features/dialog-manager/actions/confirm-ability-score-dialog.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
  src/features/dialog-manager/dialogs/game-text-dialog/index.js
  src/features/stats/reducer.js
  src/features/world/actions/start-main-game.js
Labels: bug, enhancement

#93 Add equip button to snackbar closes #64
  src/features/snackbar/index.js
  src/features/snackbar/reducer.js
  src/features/snackbar/styles.scss
Labels: design, enhancement, usability

#98 Change snackbar notifications closes #83
  src/features/snackbar/index.js
Labels: enhancement, usability

#100 Update z-index of snackbar closes #81
  src/features/snackbar/index.js
Labels: enhancement, usability

#101 Character creation closes #45 #50
  src/components/button/index.js
  src/components/button/styles.scss
  src/components/select-button/index.js
  src/features/dialog-manager/actions/create-character.js
  src/features/dialog-manager/actions/set-class.js
  src/features/dialog-manager/actions/set-race.js
  src/features/dialog-manager/dialogs/character-creation/index.js
  src/features/dialog-manager/dialogs/character-creation/styles.scss
  src/features/dialog-manager/index.js
  src/features/dialog-manager/reducer.js
  src/features/player/controls.js
  src/features/world/actions/start-main-game.js
Labels: Medium Priority, feature

#109 Hotkey to open and close inventory
  src/components/dialog/index.js
  src/features/dialog-manager/dialogs/inventory-dialog/index.js
  src/features/inventory/index.js
  src/features/player/controls.js
Labels: feature, usability

#112 Wisdom stat affects health restored through potions
  src/components/view-item/index.js
  src/data/items/other/great-hp-potion/index.js
  src/data/items/other/hp-potion/index.js
  src/utils/calculate-wisdom-potion-bonus.js
Labels: design, feature

#111 Enhancement/toggle ability dialog
  src/config/constants.js
  src/features/dialog-manager/actions/ability-score-dialog.js
  src/features/dialog-manager/actions/confirm-ability-score-dialog.js
  src/features/dialog-manager/actions/set-ability-scores.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/dialog-manager/reducer.js
  src/features/player/controls.js
  src/features/stats/reducer.js
Labels: enhancement

#114 Replace key code values with macros closes #110
  src/components/dialog/index.js
  src/components/micro-dialog/index.js
  src/config/constants.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
  src/features/dialog-manager/dialogs/inventory-dialog/index.js
  src/features/player/controls.js
Labels: enhancement

#113 Intelligence stat affects total mana pool
  src/features/stats/index.js
  src/features/stats/reducer.js
  src/utils/calculate-max-mana-pool.js
Labels: design, feature

#122 Remove title for bug report closes #121
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug

#118 Add key to select buttons to resolve #117
  src/components/select-button-group/index.js
Labels: bug

#106 Refactor character creation fixes #105
  src/features/dialog-manager/dialogs/character-creation/actions/create-character.js
  src/features/dialog-manager/dialogs/character-creation/actions/set-class.js
  src/features/dialog-manager/dialogs/character-creation/actions/set-race.js
  src/features/dialog-manager/dialogs/character-creation/index.js
  src/features/dialog-manager/reducer.js
Labels: bug

#116 Error Message Displays on Empty Name
  src/features/dialog-manager/actions/error-message.js
  src/features/dialog-manager/dialogs/character-creation/actions/create-character.js
  src/features/dialog-manager/dialogs/character-creation/index.js
  src/features/snackbar/index.js
  src/features/snackbar/reducer.js
Labels: Low Priority, enhancement

#120 Feature/constitution closes #59
  src/config/constants.js
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/stats/reducer.js
  src/utils/calculate-max-hp-pool.js
Labels: Medium Priority, feature

#125 Prevent Rusty Sword from showing equip snackbar resolves #124
  src/features/snackbar/index.js
Labels: bug

#119 Initial Implementation of a Save and Load System
  src/features/app-state/reducer.js
  src/features/dialog-manager/actions/load-game.js
  src/features/dialog-manager/dialogs/game-select/index.js
  src/features/dialog-manager/dialogs/game-select/styles.scss
  src/features/dialog-manager/dialogs/settings-dialog/index.js
  src/features/dialog-manager/dialogs/settings-dialog/settings-dialog.scss
  src/features/dialog-manager/reducer.js
  src/features/game-menus/reducer.js
  src/features/inventory/reducer.js
  src/features/map/reducer.js
  src/features/monsters/reducer.js
  src/features/player/controls.js
  src/features/player/reducer.js
  src/features/snackbar/actions/clear-notification.js
  src/features/snackbar/index.js
  src/features/snackbar/reducer.js
  src/features/stats/reducer.js
  src/features/world/reducer.js
Labels: feature

#127 Enhancement/character name closes #102
  src/data/maps/1_1/index.js
  src/data/maps/1_3/index.js
  src/data/maps/2_1/index.js
  src/data/maps/2_3/index.js
  src/data/maps/2_5/index.js
  src/features/dialog-manager/index.js
  src/features/map/random-map-gen/random-map-message.js
  src/features/stats/index.js
  src/features/stats/reducer.js
  src/features/stats/styles.scss
  src/features/world/actions/start-endless-game.js
Labels: Low Priority, enhancement

#126 Modify shop buy/sell prices based on charisma closes #56
  src/components/shop-inventory/index.js
  src/components/shop-inventory/shop-item/index.js
  src/components/view-item/index.js
  src/features/inventory/actions/buy-item.js
  src/features/inventory/actions/sell-item.js
  src/utils/calculate-buy-price.js
  src/utils/calculate-sell-price.js
Labels: design, feature

#130 Enhancement/fix readme
  README.md
Labels: enhancement

#137 Add Sold Item Notification
  src/features/inventory/actions/sell-item.js
  src/features/inventory/reducer.js
  src/features/snackbar/index.js
  src/features/snackbar/reducer.js
Labels: enhancement

#134 Add hotkey for equipping items closes #131
  src/components/dialog/index.js
  src/config/constants.js
  src/features/snackbar/index.js
Labels: feature, usability

#133 Race changes starting ability scores and hide increment and decrement on max and min values
  src/components/ability/index.js
  src/config/constants.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
  src/features/dialog-manager/reducer.js
  src/utils/add-race-ability-bonus.js
  src/utils/reset-starting-abilities.js
  src/utils/set-ability-minimum.js
  src/utils/set-race-bonus.js
Labels: enhancement, usability

#139 Implement Usage of Dice Rolls for Damage Calculations
  src/components/view-item/index.js
  src/components/view-item/stats-item/index.js
  src/data/items/weapons/broad-sword/index.js
  src/data/items/weapons/dragons-bane/index.js
  src/data/items/weapons/lich-bane/index.js
  src/data/items/weapons/rusty-sword/index.js
  src/data/items/weapons/steel-sword/index.js
  src/features/player/actions/attack-monster.js
  src/utils/dice.js
Labels: design, feature

#141 Dice based combat
  src/config/constants.js
  src/data/items/weapons/rusty-sword/index.js
  src/data/items/weapons/steel-sword/index.js
  src/data/monsters/dragon/index.js
  src/data/monsters/goblin/index.js
  src/data/monsters/imp/index.js
  src/data/monsters/lich/index.js
  src/data/monsters/rat/index.js
  src/data/monsters/stone-golem/index.js
  src/features/dialog-manager/actions/error-message.js
  src/features/dialog-manager/dialogs/game-over/index.js
  src/features/monsters/actions/attack-player.js
  src/features/monsters/actions/take-monsters-turn.js
  src/features/player/actions/attack-monster.js
  src/features/snackbar/index.js
  src/features/snackbar/reducer.js
  src/features/stats/reducer.js
  src/utils/dice.js
Labels: design, feature

#144 Fix Dice Roll Parsing
  src/__tests__/utils/calculate_dice.js
  src/features/player/actions/attack-monster.js
  src/utils/dice.js
Labels: bug

#147 Fix import error closes #146
  src/features/monsters/actions/attack-player.js
Labels: bug

#149 Fix dice warnings fixes #148
  src/utils/dice.js
Labels: bug

#145 Implement character customisation closes #46
  README.md
  package.json
  src/components/colour-picker/index.js
  src/components/select-colour/index.js
  src/components/select-colour/styles.scss
  src/features/dialog-manager/dialogs/character-creation/actions/create-character.js
  src/features/dialog-manager/dialogs/character-customisation/actions/finish-customisation.js
  src/features/dialog-manager/dialogs/character-customisation/actions/set-armour-colour.js
  src/features/dialog-manager/dialogs/character-customisation/actions/set-clothes-colour.js
  src/features/dialog-manager/dialogs/character-customisation/actions/set-eye-colour.js
  src/features/dialog-manager/dialogs/character-customisation/actions/set-hair-colour.js
  src/features/dialog-manager/dialogs/character-customisation/actions/set-skin-colour.js
  src/features/dialog-manager/dialogs/character-customisation/character/assets/player-armour-big.png
  src/features/dialog-manager/dialogs/character-customisation/character/assets/player-clothes-big.png
  src/features/dialog-manager/dialogs/character-customisation/character/assets/player-eyes-big.png
  src/features/dialog-manager/dialogs/character-customisation/character/assets/player-hair-big.png
  src/features/dialog-manager/dialogs/character-customisation/character/assets/player-outline-big.png
  src/features/dialog-manager/dialogs/character-customisation/character/assets/player-skin-big.png
  src/features/dialog-manager/dialogs/character-customisation/character/index.js
  src/features/dialog-manager/dialogs/character-customisation/character/styles.scss
  src/features/dialog-manager/dialogs/character-customisation/index.js
  src/features/dialog-manager/dialogs/character-customisation/styles.scss
  src/features/dialog-manager/index.js
  src/features/dialog-manager/reducer.js
  src/features/player/assets/player-armour.png
  src/features/player/assets/player-clothes.png
  src/features/player/assets/player-eyes.png
  src/features/player/assets/player-hair.png
  src/features/player/assets/player-outline.png
  src/features/player/assets/player-skin.png
  src/features/player/index.js
  yarn.lock
Labels: asset, feature

#157 Hide buttons at 0 ability points
  src/components/ability/index.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
Labels: enhancement, usability

#164 Remove 'attack' References from Dialogs and Items
  src/data/items/rings/amethyst-ring/index.js
  src/data/items/rings/diamond-ring/index.js
  src/data/items/rings/old-ring/index.js
  src/data/monsters/dragon/index.js
  src/data/monsters/goblin/index.js
  src/data/monsters/imp/index.js
  src/data/monsters/lich/index.js
  src/data/monsters/rat/index.js
  src/data/monsters/stone-golem/index.js
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/journal/reducer.js
  src/features/monsters/actions/attack-player.js
  src/features/monsters/actions/take-monsters-turn.js
  src/features/player/actions/attack-monster.js
  src/features/stats/reducer.js
Labels: enhancement

#172 Add base mana/hp that increases with level resolves #170, #171
  src/config/constants.js
  src/features/dialog-manager/dialogs/level-up/index.js
  src/features/dialog-manager/dialogs/level-up/styles.scss
  src/features/stats/reducer.js
  src/utils/calculate-max-hp-pool.js
  src/utils/calculate-max-mana-pool.js
Labels: bug, enhancement

#160 Initial Implementation of Spellcasting System
  README.md
  package.json
  src/components/spell/index.js
  src/config/constants.js
  src/data/spells/fireball/Fireball.png
  src/data/spells/fireball/index.js
  src/data/spells/index.js
  src/data/spells/mend/Mend.png
  src/data/spells/mend/index.js
  src/features/dialog-manager/actions/set-active-spell.js
  src/features/dialog-manager/actions/toggle-spellbook-dialog.js
  src/features/dialog-manager/dialogs/spellbook-dialog/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/styles.scss
  src/features/dialog-manager/index.js
  src/features/dialog-manager/reducer.js
  src/features/journal/reducer.js
  src/features/player/actions/attack-monster.js
  src/features/player/actions/cast-spell.js
  src/features/player/controls.js
  src/features/player/index.js
  src/features/player/reducer.js
  src/features/player/styles.scss
  src/features/stats/reducer.js
  yarn.lock
Labels: discuss, feature

#180 Enhancement/selling price info
  src/components/view-item/index.js
  src/components/view-item/stats-item/index.js
Labels: Low Priority, enhancement

#161 Add Back Buttons to Starting Dialogs, Keyboard Shortcuts to Dialogs
  src/components/confirm-dialog/index.js
  src/components/dialog/index.js
  src/components/micro-dialog/index.js
  src/components/view-item/index.js
  src/config/constants.js
  src/features/dialog-manager/actions/back-to-character-creation.js
  src/features/dialog-manager/actions/back-to-character-customisation.js
  src/features/dialog-manager/actions/close-chest-dialog.js
  src/features/dialog-manager/actions/show-endless-message.js
  src/features/dialog-manager/dialogs/ability-dialog/index.js
  src/features/dialog-manager/dialogs/ability-dialog/styles.scss
  src/features/dialog-manager/dialogs/character-creation/index.js
  src/features/dialog-manager/dialogs/character-creation/styles.scss
  src/features/dialog-manager/dialogs/character-customisation/index.js
  src/features/dialog-manager/dialogs/character-customisation/styles.scss
  src/features/dialog-manager/dialogs/game-instructions/index.js
  src/features/dialog-manager/dialogs/game-over/index.js
  src/features/dialog-manager/dialogs/inventory-dialog/index.js
  src/features/dialog-manager/dialogs/journal-dialog/index.js
  src/features/dialog-manager/dialogs/settings-dialog/index.js
  src/features/dialog-manager/dialogs/shop-dialog/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/index.js
  src/features/dialog-manager/reducer.js
  src/features/inventory/actions/pickup-item.js
  src/features/player/controls.js
  src/features/snackbar/index.js
  src/features/world/actions/start-endless-game.js
Labels: enhancement

#156 Add defence to UI
  src/features/stats/index.js
  src/features/stats/styles.scss
Labels: enhancement, usability

#179 Add Buttons for Casting Active Spell and Opening Spellbook to UI
  src/App.js
  src/components/button/index.js
  src/components/button/styles.scss
  src/components/spell/index.js
  src/components/view-item/index.js
  src/components/view-item/stats-item/index.js
  src/components/view-item/stats-item/styles.scss
  src/data/spells/fireball/Fireball-image.png
  src/data/spells/fireball/Fireball.png
  src/data/spells/fireball/index.js
  src/data/spells/mend/Mend-image.png
  src/data/spells/mend/Mend.png
  src/data/spells/mend/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/spell-button/index.js
  src/features/dialog-manager/dialogs/spellbook-dialog/spell-button/styles.scss
  src/features/dialog-manager/dialogs/spellbook-dialog/styles.scss
  src/features/spellbook/index.js
  src/features/spellbook/styles.scss
Labels: feature, usability

#169 Change how prices are calculated fixes #167
  src/components/shop-inventory/shop-item/index.js
  src/components/view-item/index.js
  src/config/constants.js
  src/features/inventory/actions/buy-item.js
  src/features/inventory/actions/sell-item.js
  src/utils/calculate-buy-price.js
  src/utils/calculate-prices.js
  src/utils/calculate-sell-price.js
Labels: bug
